### ISSUE TITLE
Video and GIF support for Discord embeds?

### ISSUE THREAD

**Issue by rossiscool123** [SergiX44/XBackBone#328]
**Is your feature request related to a problem? Please describe.**
There's currently no embed support for GIF's and Videos in the newest release 3.3.4.

**Describe the solution you'd like**
Videos and GIF's actually embedding inside of Discord rather than just showing the embed meta tags.

**Additional context**
It is possible from a longshot, I've done some testing on my end and managed to get a video to embed from steamable and partially get working with local video files. I gone through the traffic using the developer options and every video file gets a status code 415, I'm assuming this format is being forced to be a jpeg. I'll post some screenshots if you cant understand my explanation.
![raw](https://user-images.githubusercontent.com/62076535/111786170-69c66580-88b5-11eb-83e7-eab592863b1e.png)
![raw (1)](https://user-images.githubusercontent.com/62076535/111786172-6a5efc00-88b5-11eb-9d97-cd066d940811.png)

**Comment by DirtyCajunRice** [comment]
Yeah this was a huge regression IMO.

**Comment by SergiX44** [comment]
Fixed in the release 3.3.5

**Comment by rossiscool123** [comment]
@SergiX44 Experimented in 3.3.5 and its not fixed. Videos will still fail to embed and just shows the embed window like this. 
![82kLRZG](https://user-images.githubusercontent.com/62076535/116159250-ceac8100-a6e7-11eb-90a5-7055c7b1774a.png)

It also doesn't like to embed under its own domain. When I uploaded a video from the same domain the result is the same as the picture above even if I hardcode the URL in, however, hardcoding from another xbackbone domain or directory works. Not sure of the reason behind this but maybe someone can take that knowledge and come up with a fix.

This is what I have in my public.twig.

![yirMBXt](https://user-images.githubusercontent.com/62076535/116159989-1da6e600-a6e9-11eb-8d26-a62a059e41c3.png)

And this is the result.
![vZCt6hV](https://user-images.githubusercontent.com/62076535/116160093-4cbd5780-a6e9-11eb-918d-ac3d30c540bb.png)

**Comment by SergiX44** [comment]
> @SergiX44 Experimented in 3.3.5 and its not fixed. Videos will still fail to embed and just shows the embed window like this.
> ![82kLRZG](https://user-images.githubusercontent.com/62076535/116159250-ceac8100-a6e7-11eb-90a5-7055c7b1774a.png)
> 
> It also doesn't like to embed under its own domain. When I uploaded a video from the same domain the result is the same as the picture above even if I hardcode the URL in, however, hardcoding from another xbackbone domain or directory works. Not sure of the reason behind this but maybe someone can take that knowledge and come up with a fix.
> 
> This is what I have in my public.twig.
> 
> ![yirMBXt](https://user-images.githubusercontent.com/62076535/116159989-1da6e600-a6e9-11eb-8d26-a62a059e41c3.png)
> 
> And this is the result.
> ![vZCt6hV](https://user-images.githubusercontent.com/62076535/116160093-4cbd5780-a6e9-11eb-918d-ac3d30c540bb.png)

I think you have something wrong on your side, I tried now with my instance upgrade to the 3.3.5 and this is the result on discord with a video: 
![image](https://user-images.githubusercontent.com/4172890/116233881-27b5fc80-a75c-11eb-9511-70eeedef2215.png)

**Comment by rossiscool123** [comment]
@SergiX44 I'm trying to achieve video embeds working with the fancy embeds that Discord supports with the meta tags. My issue is in relation to that, not the regular embeds Discord do themselves.
