### ISSUE TITLE
sorting is not working

### ISSUE THREAD

**Issue by darkzero-sdz** [SergiX44/XBackBone#448]
**Expected Behavior**
sorting of images via tags/size/name

**Current Behavior**
page reloads, but nothing changes

**Steps to Reproduce**
1.install this docker image on Synology via Portainer or Script
2.upload some images, give them tags
3.try to sort these images
4.nothing changes

**Environment**
OS: DSM7
CPU architecture: arm64

**How docker service was installed:**

from portainer (docker compose) or via synology tasks (cli)

**Docker logs**
no error messages in logs

**Comment by rubenixnagios** [comment]
same problem here on linuxserver.io docker image running armv7 (rpi 4 8GB) behind NPM as a reverse proxy
also attempted with both mysql and sqllite backends, same exact results
hope someone finds a fix!

**Comment by GilbN** [comment]
This should be fixed now for the lsio image.

**Comment by Sloth-on-meth** [comment]
this issue is still occuring for me on the latest lsio image
